Second pull request
MikaIsaak/NFT-Marketplace pull request #2
Opened 2024-02-12 11:34 UTC by MikaIsaak

2024-02-13 16:27 UTC, maksimKrukovich commented on contracts/ERC721/MarcChagall.sol
> +import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
Invalid import syntax

2024-02-13 16:28 UTC, maksimKrukovich commented on contracts/ERC721/MarcChagall.sol
> +    function initialize(address initialOwner) public initializer {
Initializer shouldn't be public

2024-02-13 16:29 UTC, maksimKrukovich commented on contracts/ERC721/MarcChagall.sol
> +    function safeMint(address to) public {
are u going to call this function inside this SC? why public

2024-02-13 16:31 UTC, maksimKrukovich commented on contracts/Marketplace/Marketplace.sol
> +    address private immutable feeAccount;
feeReceiver is better

2024-02-13 16:32 UTC, maksimKrukovich commented on contracts/Marketplace/Marketplace.sol
> -contract Marketplace is ReentrancyGuard {
Why marketplace is not upgradeable?

2024-02-13 16:33 UTC, maksimKrukovich commented on contracts/Marketplace/Marketplace.sol
> +    MarcChagall nft;
Where is visible scope

2024-02-13 16:37 UTC, maksimKrukovich requested changes
fix

2024-02-26 13:08 UTC, Plaksaaa commented on contracts/Marketplace/Marketplace.sol
> +        USDC.transferFrom(msg.sender, address(this), totalPrice);
You transfer funds before bid execution, it seems not user friendly cause i can pay tx fee for nothing

2024-02-26 13:12 UTC, Plaksaaa commented on contracts/Marketplace/Marketplace.sol
> +        bid.price = 0;
Why do you set the price to zero if you delete whole bid from mapping in the end of the function

2024-02-27 13:42 UTC, MikaIsaak commented on contracts/Marketplace/Marketplace.sol
> +        bid.price = 0;
Reentrancy hack can't be made using this function? Because i saw some hack patterns, where we first of all send money and then make balance zero. In fact, in our function, if we delete 142 line we can see the same situation, can't we? Maybe in deleting situation it works in other way. I will be grateful, if you go deep in this case

2024-02-27 13:51 UTC, MikaIsaak commented on contracts/Marketplace/Marketplace.sol
> +        USDC.transferFrom(msg.sender, address(this), totalPrice);
We can meet situation when buyer at the bid execution moment don't have enough funds for bid that he made. That is why i consider keep money in the contract. I saw that i don't have refund during "cancelBid" function, but i will add it in the next commit

2024-02-28 11:50 UTC, MikaIsaak commented on contracts/Marketplace/Marketplace.sol
> +        bid.price = 0;
Sorry, I forgot that we work with USDC for a moment and reentrancy is unreal, i will change it

2024-07-12 05:38 UTC, closed without merging